services:
  app:
    image: pawprint:dev
    volumes:
      - .:/app
      - ~/.gnupg:/root/.gnupg
    working_dir: /app
    command: uv run manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    